Models/ErrorViewModel.cs
using System;

namespace MyFirstAppASP.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Personal.cs
using System;

namespace MyFirstAppASP.Models
{
    public class Personal
    {
        public string profession;
        public string experience;
        public string phone;
        public string email;
        public string location;
        public string name;
        public string lastname;
        public int age;
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyFirstAppASP.Models;

namespace MyFirstAppASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PersonalController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyFirstAppASP.Models;

namespace MyFirstAppASP.Controllers
{
    public class PersonalController : Controller
    {
        public IActionResult Index()
        {
            Personal personal = new Personal();
            personal.profession = "Student";
            personal.experience = "1 Year";
            personal.phone = "+503 7470-8027";
            personal.email = "SMIS055621@UGB.EDU.SV";
            personal.location = "Santa Rosa de Lima, La Union, El Salvador, Centroamerica.";
            personal.name ="Cesar";
            personal.lastname ="Martinez";
            personal.age=20;
            return View(personal);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    
</style>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Personal/Index.cshtml
@{
ViewData["Title"] = "Personal Page";
}
@model Personal

<div class="body">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
        integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-md-6">
                <div class="mb-2">
                    <img class="w-100" src="~/img/Cesar.png" alt="">
                </div>
                <div class="mb-2 d-flex">
                    <h4 class="font-weight-normal"><b>@Model.name @Model.lastname</b></h4>
                    <div class="social d-flex ml-auto">
                        <p class="pr-2 font-weight-normal">Follow me:</p>
                        <a href="https://github.com/CesarMartinez23" class="text-muted mr-1">
                            <i class="fab fa-github"></i>
                        </a>
                        <a href="https://twitter.com/cesarmartinez_j" class="text-muted mr-1">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="https://www.instagram.com/cesarmartinez_jr" class="text-muted mr-1">
                            <i class="fab fa-instagram"></i>
                        </a>
                    </div>
                </div>
                <div class="mb-2">
                    <ul class="list-unstyled">
                        <li class="media">
                            <span class="w-25 text-black font-weight-normal">Profession:</span>
                            <label class="media-body">@Model.profession</label>
                        </li>
                        <li class="media">
                            <span class="w-25 text-black font-weight-normal">Experience: </span>
                            <label class="media-body">@Model.experience</label>
                        </li>
                        <li class="media">
                            <span class="w-25 text-black font-weight-normal">Phone: </span>
                            <label class="media-body">@Model.phone</label>
                        </li>
                        <li class="media">
                            <span class="w-25 text-black font-weight-normal">Email: </span>
                            <label class="media-body">@Model.email</label>
                        </li>
                        <li class="media">
                            <span class="w-25 text-black font-weight-normal">Location: </span>
                            <label class="media-body">@Model.location</label>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-7 col-md-6 pl-xl-3">
                <h5 class="font-weight-normal"><b>Biography of C&eacute;sar Martinez</b></h5>
                <p>I am a person passionate about the world of technology and programming, I am focused on Web Development as Frontend Developer, I also dedicate myself to researching, learning and practicing new technologies focused on web development, I am dedicated to learning and sharing my knowledge with others, I currently lead a community called the Google Developer Student Club UGB..</p>
                <div class="my-2 bg-light p-2">
                    <p class="font-italic mb-0">"Controlling complexity is the essence of programming"
                        <br>-- Brian Kernigan</p>
                </div>
                <h5 class="font-weight-normal"><b>My Hobbies</b></h5>
                <ul class="list list-unstyled mb-3">
                    <li class="text-secondary font-weight-normal mb-1">
                        <span class="ti-arrow-right pr-1 text-primary"></span>
                        -Programming.
                    </li>
                    <li class="text-secondary font-weight-normal mb-1">
                        <span class="ti-arrow-right pr-1 text-primary"></span>
                        -Play Basketball.
                    </li>
                    <li class="text-secondary font-weight-normal mb-1">
                        <span class="ti-arrow-right pr-1 text-primary"></span>
                        -Watch YouTube videos about technology. 
                    </li>
                    <li class="text-secondary font-weight-normal mb-1">
                        <span class="ti-arrow-right pr-1 text-primary"></span>
                        -To Study.
                    </li>
                </ul>
                <h5 class="font-weight-normal"><b>Personal Experience</b></h5>
                <p><b>Gerardo Barrios University, San Miguel, El Salvador.</b><br>
                    • Computer Systems and Networks Engineering. <br>
                (Currently studying 1st year).</p>
                <div class="mb-2 mt-2 pt-1">
                    <h5 class="font-weight-normal"><b>Skills</b></h5>
                    <br>
                </div>
                <div class="py-1">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width:45%" aria-valuenow="45"
                            aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar-title">HTML</div>
                            <span class="progress-bar-number">45%</span>
                        </div>
                    </div>
                </div>
                <div class="py-1">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width:50%" aria-valuenow="50"
                            aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar-title">CSS</div>
                            <span class="progress-bar-number">50%</span>
                        </div>
                    </div>
                </div>
                <div class="py-1">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width:15%" aria-valuenow="15"
                            aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar-title">JavaScript</div>
                            <span class="progress-bar-number">15%</span>
                        </div>
                    </div>
                </div>
                <div class="py-1">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width:25%" aria-valuenow="25"
                            aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar-title">PHP</div>
                            <span class="progress-bar-number">25%</span>
                        </div>
                    </div>
                </div>
                <div class="py-1">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width:75%" aria-valuenow="75"
                            aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar-title">MySQL</div>
                            <span class="progress-bar-number">75%</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Cars.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"] - Cars</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet"/>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Personal" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-car"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Cars</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Home -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Personal" asp-action="Index">
                    <i class="fas fa-house-user"></i>
                    <span>Home</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <div class="sidebar-heading">
                Car Table
            </div>

            <!-- Nav Item - Brand Car -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Personal" asp-action="Index">
                    <i class="fas fa-bookmark"></i>
                    <span>Brand Car</span></a>
            </li>

            <!-- Nav Item - Model Car -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Personal" asp-action="Index">
                    <i class="fas fa-tachometer-alt"></i>
                    <span>Model Car</span></a>
            </li>

            <!-- Nav Item - Year Car -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Personal" asp-action="Index">
                    <i class="far fa-calendar"></i>
                    <span>Year Car</span></a>
            </li>

            <!-- Nav Item - Color Car -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Personal" asp-action="Index">
                    <i class="fas fa-palette"></i>
                    <span>Color Car</span></a>
            </li>
            
            <!-- Nav Item - Type Car -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Personal" asp-action="Index">
                    <i class="fas fa-search"></i>
                    <span>Type Car</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Car Options
            </div>

            <!-- Nav Item - Page Car Options Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-car"></i>
                    <span>Car Options</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Actions:</h6>
                        <a class="collapse-item" href="#"><i class="fas fa-car"></i><span> New Car</span></a>
                        <a class="collapse-item" href="#"><i class="fas fa-list-ul"></i><span> List Car</span></a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                My Personal Page
            </div>

            <!-- Nav Item - Personal Page -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Personal" asp-action="Index">
                    <i class="fas fa-user"></i>
                    <span>Personal Page</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search Car..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>   

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Cesar Martinez</span>
                                <img class="img-profile rounded-circle"
                                    src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->
                    

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Programacion Computacional I 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script> 


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html> 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstAppASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFirstAppASP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personal"
                                asp-action="Index">Personal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Programacion Computacional I - <a asp-area="" asp-controller="Home"
                asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>